### ISSUE TITLE
배포 페이지 application 에러 발생

### ISSUE THREAD

**Issue by 55555-Jyeon** [ThugDev/PurrTunes#13]
<img width="2239" alt="Screenshot 2024-09-07 at 2 39 28 AM" src="https://github.com/user-attachments/assets/1ea90318-c8d5-45ab-9fbd-1d5926a6c38e">

**Comment by 55555-Jyeon** [comment]
###### [🔥HOTFIX : add environment variables and fix design errors](https://github.com/ThugDev/PurrTunes/commit/4d4eb4cf2e44365d30f1e2f334a54045cd7c8f9e)

해당 에러는 환경 변수에서 일부 내용이 vercel에서 누락돼 있어서 생기는 에러였습니다!
vercel 페이지에 누락된 환경 변수 전부 추가했고 페이지 정상적으로 보여지고 있습니다 :)

퍼블리싱된 디자인 중 틀어지는 부분(header)와 lucide 아이콘 적용되지 않은 searchModal의 닫기 버튼 이미지 변경했습니다!

**Comment by ijimlnosk** [comment]
오...!
고생하셨습니다!!
